apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workder
spec:
  destination:
    namespace: simple-love
    server: https://kubernetes.default.svc
  source:
    path: charts/worker
    repoURL: https://github.com/minhlk/k8s-eks
    targetRevision: main
    helm:
      valueFiles:
        - /env/dev/worker/workder-values.yml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
