namespace: simple-love-prod
replicaCount: 1

image:
  repository: mysql:lts
  pullPolicy: IfNotPresent
  port: 3306
  tag: ""

service:
  type: ClusterIP
  port: 3306

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    memory: 128Mi
