namespace: simple-love
replicaCount: 2

image:
  repository: minhlk/k8s-backend:v1.3
  port: 9000
  tag: "1.0.0"

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    memory: 128Mi
