namespace: simple-love-dev
replicaCount: 2

image:
  repository: minhlk/k8s-backend
  port: 9000
  tag: "010adac"

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 512Mi
