namespace: simple-love
replicaCount: 1

image:
  repository: minhlk/k8s-frontend:v2
  port: 80
  tag: "1.0.0"

service:
  type: ClusterIP
  port: 80

resources: {}

metrics:
  target:
    averageUtilization: 40