apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: db
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
