apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-love-ingress
  namespace: simple-love
spec:
  rules:
    - host: simple-love.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
