apiVersion: v1
kind: Namespace
metadata:
  name: simple-love-dev

---
apiVersion: v1
kind: Namespace
metadata:
  name: simple-love-prod

---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---
apiVersion: v1
kind: Namespace
metadata:
  name: simple-love-monitoring-dev

---
apiVersion: v1
kind: Namespace
metadata:
  name: simple-love-monitoring-prod
