grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: false
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://simple-love-loki:3100
      isDefault: true
      jsonData:
        maxLines: 1000
promtail:
  enabled: true
  config:
    clients:
      - url: http://simple-love-loki:3100/loki/api/v1/push