apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.image.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "" }}
              memory: {{ .Values.resources.requests.memory | default "" }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "" }}
              memory: {{ .Values.resources.limits.memory | default "" }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
