namespace: example-namespace
replicaCount: 1

service:
  type: ClusterIP
  port: 3306

resources: {}

grafana:
  sidecar: {}
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://{{ .Release.Name }}-loki:3100
        jsonData:
          maxLines: 1000
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ .Release.Name }}-prometheus-server:80
        isDefault: true
        jsonData:
          maxLines: 1000

loki-stack:
  loki:
    image:
      tag: 2.9.3
  promtail:
    enabled: true
    config:
      clients:
        - url: http://{{ .Release.Name }}-loki:3100/loki/api/v1/push
