namespace: simple-love
replicaCount: 1

service:
  type: ClusterIP
  port: 3306

resources: {}

grafana:
  datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://{{ .Release.Name }}:3100
      isDefault: true
      jsonData:
        maxLines: 1000

loki-stack:
  loki:
    image:
      tag: 2.9.3
  promtail:
    enabled: true
    config:
      clients:
        - url: http://{{ .Release.Name }}:3100/loki/api/v1/push
