apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}
          ports:
            - containerPort: {{ .Values.image.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.namespace }}-secret
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "" }}
              memory: {{ .Values.resources.requests.memory | default "" }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "" }}
              memory: {{ .Values.resources.limits.memory | default "" }}
