apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: {{ .Release.Name }}-svc
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
