namespace: simple-love-prod
replicaCount: 2

image:
  repository: minhlk/k8s-frontend
  port: 80
  tag: "8278992"

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 512Mi

metrics:
  target:
    averageUtilization: 40