apiVersion: v2
name: db
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
- name: nats
  version: "1.3.13"
  repository: "https://nats-io.github.io/k8s/helm/charts/"