apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        configmap.reloader.stakater.com/reload: "{{ .Values.namespace }}-configmap"
        secret.reloader.stakater.com/reload: "{{ .Values.namespace }}-secret"
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          envFrom:
            - secretRef:
                name: {{ .Values.namespace }}-secret
            - configMapRef:
                name: {{ .Values.namespace }}-configmap
