name: Reusable Build and Push
on:
  workflow_call:
    inputs:
      service:
        description: 'The service to build (e.g., backend or frontend)'
        required: true
        type: string

env:
  DOCKER_HUB_USERNAME: minhlk

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Tag image
        run: |
          IMAGE=k8s-${{ inputs.service }}
          TAG=${GITHUB_SHA::7}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: application/${{ inputs.service }}
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE }}:latest

      - name: Update Helm values
        run: |
          sed -i "s|tag:.*|tag: \"$IMAGE_TAG\"|" env/dev/${{ inputs.service }}/${{ inputs.service }}-values.yml
      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Update ${{ inputs.service }} image tag to $IMAGE_TAG"
          git push
