name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      worker: ${{ steps.filter.outputs.worker }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'application/backend/**'
            frontend:
              - 'application/frontend/**'
            worker:
              - 'application/worker/**'

  build-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    uses: ./.github/workflows/docker-ci.yml
    with:
      service: backend
    secrets: inherit

  build-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    uses: ./.github/workflows/docker-ci.yml
    with:
      service: frontend
    secrets: inherit
  
  build-worker:
    needs: detect-changes
    if: needs.detect-changes.outputs.worker == 'true'
    uses: ./.github/workflows/docker-ci.yml
    with:
      service: worker
    secrets: inherit
